# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/toor/tp_game_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/toor/tp_game_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toor/tp_game_project/CMakeFiles /home/toor/tp_game_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/toor/tp_game_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WorldState

# Build rule for target.
WorldState: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WorldState
.PHONY : WorldState

# fast build rule for target.
WorldState/fast:
	$(MAKE) -f build/src/CMakeFiles/WorldState.dir/build.make build/src/CMakeFiles/WorldState.dir/build
.PHONY : WorldState/fast

#=============================================================================
# Target rules for targets named Enemy

# Build rule for target.
Enemy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Enemy
.PHONY : Enemy

# fast build rule for target.
Enemy/fast:
	$(MAKE) -f build/src/CMakeFiles/Enemy.dir/build.make build/src/CMakeFiles/Enemy.dir/build
.PHONY : Enemy/fast

#=============================================================================
# Target rules for targets named Warrior

# Build rule for target.
Warrior: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Warrior
.PHONY : Warrior

# fast build rule for target.
Warrior/fast:
	$(MAKE) -f build/src/CMakeFiles/Warrior.dir/build.make build/src/CMakeFiles/Warrior.dir/build
.PHONY : Warrior/fast

#=============================================================================
# Target rules for targets named Archer

# Build rule for target.
Archer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Archer
.PHONY : Archer

# fast build rule for target.
Archer/fast:
	$(MAKE) -f build/src/CMakeFiles/Archer.dir/build.make build/src/CMakeFiles/Archer.dir/build
.PHONY : Archer/fast

#=============================================================================
# Target rules for targets named WarriorFactory

# Build rule for target.
WarriorFactory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WarriorFactory
.PHONY : WarriorFactory

# fast build rule for target.
WarriorFactory/fast:
	$(MAKE) -f build/src/CMakeFiles/WarriorFactory.dir/build.make build/src/CMakeFiles/WarriorFactory.dir/build
.PHONY : WarriorFactory/fast

#=============================================================================
# Target rules for targets named ArcherFactory

# Build rule for target.
ArcherFactory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ArcherFactory
.PHONY : ArcherFactory

# fast build rule for target.
ArcherFactory/fast:
	$(MAKE) -f build/src/CMakeFiles/ArcherFactory.dir/build.make build/src/CMakeFiles/ArcherFactory.dir/build
.PHONY : ArcherFactory/fast

#=============================================================================
# Target rules for targets named EnemySpawner

# Build rule for target.
EnemySpawner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EnemySpawner
.PHONY : EnemySpawner

# fast build rule for target.
EnemySpawner/fast:
	$(MAKE) -f build/src/CMakeFiles/EnemySpawner.dir/build.make build/src/CMakeFiles/EnemySpawner.dir/build
.PHONY : EnemySpawner/fast

#=============================================================================
# Target rules for targets named EnemyFactory

# Build rule for target.
EnemyFactory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EnemyFactory
.PHONY : EnemyFactory

# fast build rule for target.
EnemyFactory/fast:
	$(MAKE) -f build/src/CMakeFiles/EnemyFactory.dir/build.make build/src/CMakeFiles/EnemyFactory.dir/build
.PHONY : EnemyFactory/fast

#=============================================================================
# Target rules for targets named executeTests

# Build rule for target.
executeTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 executeTests
.PHONY : executeTests

# fast build rule for target.
executeTests/fast:
	$(MAKE) -f build/tests/CMakeFiles/executeTests.dir/build.make build/tests/CMakeFiles/executeTests.dir/build
.PHONY : executeTests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... WorldState"
	@echo "... Enemy"
	@echo "... Warrior"
	@echo "... Archer"
	@echo "... WarriorFactory"
	@echo "... ArcherFactory"
	@echo "... EnemySpawner"
	@echo "... EnemyFactory"
	@echo "... executeTests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

